apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cosign-japower
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/japower-tenant/cosign/cosign-japower@sha256:9d4895f01115736ef3c57351eb0016a30cb24131956102c406c6947d1e5a4732
        name: container-image
        resources: {}
status: {}
