apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cosign-japower
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cosign-japower
    app.kubernetes.io/part-of: cosign
  name: cosign-japowerrv8e
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cosign-japower
    weight: 100
status: {}
