apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cosign-japower
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cosign-japower
    app.kubernetes.io/part-of: cosign
  name: cosign-japower
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cosign-japower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cosign-japower
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/japower-tenant/cosign/cosign-japower@sha256:84f90d6024b35f1832da05f93f6c68a779764b3a83c180e80b9821cbc3d2f8dd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
